backend/feat: #769 version label for middleware metrics
nammayatri/shared-kernel pull request #112
Opened 2023-05-10 10:38 UTC by roman-bodavskiy

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
https://github.com/nammayatri/nammayatri/issues/769

To do staggered deployments, we need to compare 4xx/ 5xx b/w the current and previous version across routes.
To monitor through Prom metrics, we need to add the version label in the metric: http_request_duration_seconds_count.

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables

## Motivation and Context

## How did you test it?
Didn't tested yet

## Checklist

- [x] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-05-10 12:08 UTC, srid commented on flake.nix
> +            prometheus-client = inputs.wai-middleware-prometheus + /prometheus-client;
You want to use https://github.com/juspay/prometheus-haskell/pull/3 and use prometheus exactly like `euler-hs` is being used, ie., via `imports` and `haskellFlakeProjectModules`.

https://github.com/nammayatri/shared-kernel/blob/12e660da6fcb5d09dc5a7b05b593a44c9583ee03/flake.nix#L24-L26

@aravindgopall @paulvictor Can we merge that PR?

2023-05-13 13:34 UTC, srid requested changes
See https://github.com/nammayatri/shared-kernel/pull/112/files#r1189810733

Let's collaborate with @aravindgopall to get that PR merged, and you can make your contributions on top of it.

2023-05-15 10:22 UTC, NikithShetty commented on flake.nix
> +    # wai-middleware-prometheus.url = "/home/roman/Projects/beckn/nammayatri/prometheus-juspay/prometheus-haskell";
Needs to be updated once the PR gets merged

2023-05-15 14:19 UTC, srid commented on flake.nix
> +            prometheus-client = inputs.wai-middleware-prometheus + /prometheus-client;
The PR is merged. @roman-bodavskiy You can just use https://github.com/juspay/prometheus-haskell/tree/more-proc-metrics like we use `euler-hs` here. No need to add any of these `source-overrides`.

2023-05-18 08:56 UTC, NikithShetty approved these changes

2023-05-18 08:59 UTC, merged