backend/feat: notification,execution&mandateDates
nammayatri/shared-kernel pull request #216
Opened 2023-08-17 14:17 UTC by aayushagarwal2001

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring
- [ ] Dependency updates

## Description

refactored fields for notification request and response
refactored fields for Execution request and response
startDate and Enddate to mandate set to 10 years
### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-08-17 15:15 UTC, 0utkarsh requested changes

2023-08-17 15:15 UTC, 0utkarsh commented on lib/mobility-core/src/Kernel/External/Payment/Interface/Juspay.hs
> +  now <- liftIO getCurrentTime
`liftIO` not needed, you may use our own `getCurrentTime`. it returns monad

2023-08-17 15:15 UTC, 0utkarsh commented on lib/mobility-core/src/Kernel/External/Payment/Interface/Juspay.hs
> +      mandate_end_date = show $ utcTimeToPOSIXSeconds (addUTCTime yearToSeconds now)
In manual pay?

2023-08-17 15:52 UTC, hkmangla approved these changes

2023-08-17 17:27 UTC, 0utkarsh requested changes

2023-08-17 17:27 UTC, 0utkarsh commented on lib/mobility-core/src/Kernel/External/Payment/Interface/Juspay.hs
> +mkCreateOrderReq :: BaseUrl -> Text -> UTCTime -> CreateOrderReq -> Juspay.CreateOrderReq
We could've calculated this time in this function itself

2023-08-18 02:27 UTC, 0utkarsh approved these changes

2023-08-18 02:27 UTC, merged