backend/feat/#3357 : Added FCM type for edit location
nammayatri/shared-kernel pull request #283
Opened 2023-10-09 13:56 UTC by JanhaviSoni

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-01 17:45 UTC, roman-bodavskiy approved these changes

2023-12-01 17:47 UTC, roman-bodavskiy commented on lib/mobility-core/src/Kernel/External/Notification/FCM/Types.hs
> +  | LOW_ACCOUNT_BALANCE
is it used?

2023-12-04 12:07 UTC, hkmangla requested changes

2023-12-04 12:07 UTC, hkmangla commented on lib/mobility-core/src/Kernel/Types/Error.hs
> +    DriverAboutToReachAtInitialPickup x -> Just $ "Driver is\"" <> show x <> "\"meters away from your initial pickup location so editing pickup location is not possible"
@JanhaviSoni Resolve this comment.

2023-12-19 10:22 UTC, hkmangla approved these changes

2023-12-19 10:22 UTC, merged