routing the bap bpp calls internally
nammayatri/shared-kernel pull request #328
Opened 2023-12-04 07:20 UTC by chakri642

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2023-12-04 11:52 UTC, chakri642 commented on lib/mobility-core/src/Kernel/Utils/Servant/Client.hs
> +  Maybe (HM.Map Text Text) ->
```
    • No instance for (hashable-1.4.3.0:Data.Hashable.Class.Hashable
                         BaseUrl)
        arising from a use of ‘HM.fromList’
    • In the first argument of ‘($)’, namely ‘HM.fromList’
      In the expression: HM.fromList $ M.toList aclEndPointMap
      In an equation for ‘internalEndPointMap’:
          internalEndPointMap = HM.fromList $ M.toList aclEndPointMap
    |
126 |   let internalEndPointMap = HM.fromList $ M.toList aclEndPointMap

    • No instance for (hashable-1.4.3.0:Data.Hashable.Class.Hashable
                         BaseUrl)
```
                         
It's telling there is no Hashable instance for the `BaseUrl` type, so I used `Text` and done parsing to baseurl

2023-12-06 06:45 UTC, NikithShetty approved these changes

2023-12-20 07:02 UTC, NikithShetty requested changes

2023-12-20 07:02 UTC, NikithShetty commented on lib/mobility-core/src/Kernel/Utils/Servant/Client.hs
> +        callApiExtractingApiError mbManagerSelector baseUrl eulerClient desc api
move `callApiExtractingApiError` to bottom of case statement by taking url as the output of the case block

2023-12-20 09:17 UTC, NikithShetty approved these changes

2023-12-20 09:17 UTC, merged