Backend/feat/cac changes rebase
nammayatri/shared-kernel pull request #429
Opened 2024-03-01 05:45 UTC by enigma-commits

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description
CAC in nammayatri

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-03-11 12:28 UTC, piyushKumar-1 commented on lib/mobility-core/src/Kernel/External/AadhaarVerification/Types.hs
> +  parseJSON _ = error "unexpected type, expected String for AadhaarVerificationService"
print the argument as well here.

2024-03-11 12:28 UTC, piyushKumar-1 commented on lib/mobility-core/src/Kernel/External/Ticket/Types.hs
> +  parseJSON _ = error "unexpected type, expected String for IssueTicketService"
same

2024-03-11 12:37 UTC, piyushKumar-1 requested changes

2024-03-11 12:37 UTC, piyushKumar-1 commented on lib/mobility-core/src/Kernel/Types/Common.hs
> +    useCAC :: [Text],
make separate config for this.

2024-03-11 12:54 UTC, piyushKumar-1 commented on lib/mobility-core/src/Kernel/External/AadhaarVerification/Types.hs
> +{-# HLINT ignore "Use lambda-case" #-}
kyu ?

2024-03-12 06:49 UTC, enigma-commits commented on lib/mobility-core/src/Kernel/Types/Cac.hs
> +  DA.Error _ -> Nothing
We simply don't care. Here In nammayatri it is handled

2024-03-12 06:53 UTC, enigma-commits commented on lib/mobility-core/src/Kernel/Types/Cac.hs
> +dropPrefixFromConfig key config =
it is actually correct key is my key which i have to drop and config is the key coming from config.

2024-03-13 08:15 UTC, piyushKumar-1 commented on lib/mobility-core/src/Kernel/Types/Cac.hs
> +  DA.Error _ -> Nothing
handling is fine, i am taking about the error information is lost. But cool take it in phase 2.

2024-03-13 08:15 UTC, piyushKumar-1 commented on lib/mobility-core/src/Kernel/Types/Common.hs
> +    useCAC :: [Text],
phase 2

2024-08-14 06:23 UTC, closed without merging