shared-kernel/enhancement/handle-fcm-token-expiry
nammayatri/shared-kernel pull request #498
Opened 2024-05-08 14:58 UTC by DwivediAman-exe

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-05-08 15:32 UTC, jaypalmudaliyar24 requested changes

2024-05-08 15:32 UTC, jaypalmudaliyar24 commented on lib/mobility-core/src/Kernel/External/Notification/FCM/Flow.hs
> +notifyPerson config action msgData recipient = notifyPersonWithPriority config Nothing action False msgData recipient EulerHS.Prelude.id
can you rename `action` at all places to something more meaningful, i.e. something like `unRegisteredFCMTokenHandler`.

2024-05-08 15:32 UTC, jaypalmudaliyar24 commented on lib/mobility-core/src/Kernel/External/Notification/FCM/Flow.hs
> +        Left clientError -> do
`logTagError fcm $ "error while sending message to person with id " <> toWhom <> " : " <> show clientError`
Should we keep this log at top so even if any failure happens we get this log atleast ?

2024-05-08 16:07 UTC, piyushKumar-1 approved these changes

2024-05-08 17:33 UTC, jaypalmudaliyar24 approved these changes

2024-05-17 12:18 UTC, piyushKumar-1 approved these changes

2024-05-23 10:38 UTC, khuzema786 approved these changes

2024-05-23 10:46 UTC, merged