backend/feat/added_diffUTC_-for_ckh
nammayatri/shared-kernel pull request #509
Opened 2024-05-22 08:56 UTC by ashishsaini25

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

backend/feat/added_diffUTC_-for_ckh
### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-05-23 10:48 UTC, roman-bodavskiy requested changes

2024-05-23 10:48 UTC, roman-bodavskiy commented on lib/mobility-core/src/Kernel/Storage/ClickhouseV2/Internal/Types.hs
> +showColumn (NominalDiffTimeToSeconds column) = "nominalDiffTimeToSeconds" <> addBrackets' (showColumn column)
did not found these functions `diffUTCTime`,  `nominalDiffTimeToSeconds` in clickhouse docs, are you sure they are correct?

2024-05-23 11:43 UTC, roman-bodavskiy commented on lib/mobility-core/src/Kernel/Storage/ClickhouseV2/Internal/Types.hs
> +showColumn (NominalDiffTimeToSeconds column) = "nominalDiffTimeToSeconds" <> addBrackets' (showColumn column)
also second function `nominalDiffTimeToSeconds` did not used in NY

2024-05-24 05:47 UTC, roman-bodavskiy commented on lib/mobility-core/src/Kernel/Storage/ClickhouseV2/ClickhouseValue.hs
> +  fromClickhouseValue = parseAsStringOrNumber @Time.NominalDiffTime
this is redundant since you use `Column a t Int`

2024-05-24 06:33 UTC, roman-bodavskiy approved these changes

2024-05-24 09:43 UTC, hkmangla approved these changes

2024-05-24 09:43 UTC, merged