backend/feat/split_settlement
nammayatri/shared-kernel pull request #613
Opened 2024-09-04 11:55 UTC by 0utkarsh

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates

## Description

### Additional Changes

- [ ] This PR modifies the database schema (database migration added)
- [ ] This PR modifies dhall configs/environment variables

## Motivation and Context

## How did you test it?

## Checklist

- [ ] I formatted the code and addressed linter errors `./dev/format-all-files.sh`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible
- [ ] I added a [CHANGELOG](/CHANGELOG.md) entry if applicable

2024-09-11 19:20 UTC, srid commented
Could you update this PR with latest commits from `main`? We now use github runners.

2024-10-01 08:14 UTC, hkmangla approved these changes

2024-10-01 10:27 UTC, hkmangla requested changes

2024-10-01 10:27 UTC, hkmangla commented on lib/mobility-core/src/Kernel/External/Payment/Interface/Types.hs
> +  { splitDetails :: [SplitDetailsResponse],
It should also Maybbe.

2024-10-01 10:27 UTC, hkmangla commented on lib/mobility-core/src/Kernel/External/Payment/Juspay/Types/Common.hs
> +  { split_details :: [SplitDetailsResponse],
Same here.

2024-10-18 11:56 UTC, khuzema786 commented on lib/mobility-core/src/Kernel/External/Payment/Interface/Types.hs
> +data Split = Split
@0utkarsh All this fields will always be sent by Juspay in SplitSettlementDetails ? Should we make it Maybe if not sure ?

2024-10-18 12:01 UTC, khuzema786 approved these changes

2024-11-16 07:27 UTC, khuzema786 approved these changes

2024-11-16 09:44 UTC, khuzema786 approved these changes

2024-11-16 09:45 UTC, merged